### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by fntst1c** [k4yt3x/orbitaldump#2]
`python orbitaldump.py -t 28 -u "D:\Stuff\ssh brute\usernames.txt" -p "D:\Stuff\ssh brute\pass2.txt" -h ###.##.###.90 --port 22 --proxies`

Gives a huge number of connection errors with any number of threads.

**Comment by kaizensecurity** [comment]
same issue here. No idea whats up with the connection error.

**Comment by Rezanans-wow** [comment]
agree, same

**Comment by k4yt3x** [comment]
Not every proxy found on ProxyScrape will actually work. That's all.
